title: 張勁晢
description: 我是一個個性直率好相處的人，為人和善老實、虛心受教、認真負責。極具耐心，對於同儕所提出的求助，我總是盡我所能的提供幫助。同時也對於自身的邏輯推理能力與自我思辨能力很有信心，在日常生活中，無論大小事，都會很自然的去思考其中所隱含的數學問題，或許一般人會覺得索然無味，但這對我來說就是一種樂趣。  
theme: jekyll-theme-tactile
